### ISSUE TITLE
vbox portabe do not run with win 10

### ISSUE THREAD

**Issue by p060477** [vboxme/Portable-VirtualBox#33]
hey runar..any ideas..??!!
you are better then houdini!!

**Comment by Forgen** [comment]
I also just experienced this.
Files are extracted successfully from virtual box installer.
On launch, Portable-Virtualbox splash shows.  A Notification appears 'right click me'.  Then Exiting Portable-Virtualbox shows.  Nothing else. How to start debugging this?

**Comment by p060477** [comment]
Runar..??!!..where have you gone..??
disappeared...
why you do not reply at all..??

**Comment by runarbu** [comment]
Good news @p060477 . Have have finally got some time to look at the Windows 10 issues.

The latest version dos run ok for me on Windows 10, but bridged networking is not working. The bridged networking issue is not easy to figure out, but I have started to investigate. I have also made a post in Stack Overflow in hope that any users there has a suggestion: 
http://stackoverflow.com/questions/33618303/installing-inf-file-in-windows-10-migrating-away-from-snetcfg-exe

**Comment by p060477** [comment]
Hi Runar!
Very nice to see you!
 
yes portablevbox works on win 10 but with these 2 issues:
 
1) drag and drop only from guest to host but not from host to guest
2) bridge network not working
 
the bridge issue is very important cause it should be very useful to be able to 
have it working
for ex using emule in vbox is impossible with nat cause you get Always 2 red crosses for server and kad
only with bridge you get the 2 crosses green
 
swith win 8.1 worked fine even if the snetcfg.exe had already some problems..
 
pls keep us update!
 
you are our only life-guard!
 
on vbox forum official they do not want to help us for portable vers..why..??
 
cheers!!


 


 
Date: Mon, 9 Nov 2015 13:14:40 -0800

**Comment by Megachip** [comment]
@runarbu did you try the sc command? https://github.com/vboxme/Portable-VirtualBox/issues/6#issuecomment-46589462

**Comment by p060477** [comment]
hi runar..pls do not disappear again in the mist..
what about the -bridge- network mode..??..
it is so important that issue..
pls do not leave us alone again..
reply!!

**Comment by p060477** [comment]
Runar..pls hit a bit..
you can't appear and disappear as you were the canterville ghost..
:(

**Comment by Megachip** [comment]
@p060477 This is an OS project. Either you fix it yourself, you pay someone to fix it or you have to wait until someone found the time to research (and hopefully fix the bug). We all have a job and life and this project is part of our small free time.

@runarbu you're right. For ini installation, he still uses snetcfg. So I think, the code will also not work in newer windows versions. Have no windows to check it :/. But in StackOverflow I've added 2 (untested) alternatives for installing inf files. He uses sc create only for `usbmon` and and `drv`.
The emule discussion is from @p060477, so hope he already tested it?

**Comment by p060477** [comment]
yes the emule topic is by me and i've tested their solution without any useful results so many days ago..
consider that with win 8.1 even if the snetcfg.exe was buggy i've found a workaround to by pass the issue making in task scheduler a task to start vbox at the start up of my pc..in that way i was able to have the drivers installed and to use bridge networking..but with the new win 10 this trick does really not work any more..

we really hope that the maintainer of this vbox portable vers will be able to solve this big issue..
cheers!

**Comment by p060477** [comment]
hi there!
..why you are disappeared again..??
why to have this sw portable is this long nightmare..??
why on the project page vbox.me is still clearly written how to have network bridged if since JULY 2015 IT IS CLEARLY - IMPOSSIBLE-..??
RUNAR..?
MEGACHIP..?
where are you..???

**Comment by p060477** [comment]
oh my poor ju-wien..!..my brother in this very frustrating NIGHTMARE..
all here seem to be DISAPPEARED
MEGACHIP..
RUNAR..
all they went away without any REPLY
what a PITY
what a SHAME

**Comment by DavidBrenner3** [comment]
Hi.

I'm a C++/Delphi programmer.
One of my latest creations is a tool called "Virtual Machine USB Boot".
It's using VirtualBox and/or QEMU to boot a real drive (mostly USB but other types too) into a virtual machine.

The official Virtual Machine USB Boot version works only with the installable VirtualBox version.
More than a year ago I thought implementing the use of portable VirtualBox too. But, for several (good) reasons, I couldn't.
One of the reasons is that the "Portable-VirtualBox.exe" starter file is slow, buggy and not very compatible with other applications trying to start VirtualBox Manager and/or VMs.
I waited for its problems to be solved but it seems they won't be...

So I thought implementing the load/unload of VirtualBox dlls/infs/services in my app + not using tools like sc/devcon/snetcfg (only Delphi code). This way it will be faster and less buggy. 
A week ago I replaced sc.exe with code and today I replaced devcon also.
But replacing snetcfg is not that easy, especially because I don't have its source code.

And now this problem with Window 10 :(

We could work together, share resources, exchange ideas and source code and so on - to make both applications better.

If you guys are interested, just let me know.

Regards,
David

PS: sorry for been mostly offtopic in this thread.

**Comment by p060477** [comment]
Hi David!

you should be our Angel to finally solve this nightmare with win 10 and portable vbox!
vbox portable now, with win 10, not really works with network bridge and also there is no
bi directional drag and drop but only from guest to host
i wrote here since months but RUNAR has been ,as a ghost, incredibly disappeared
so now you seem the only one able to solve those ,so very old ,bugs!
pls let us know here yr steps!
cheers!!

**Comment by DavidBrenner3** [comment]
Well, I'll do my best to solve it, but you realize I cannot guarantee I will.
As I said, replacing snetcfg is not that easy without its source code.

**Comment by Forgen** [comment]
Hi David,
Your Project sounds cool,  do you have a code repo up to share?

@p060477, what are you so desperately using thus application for that you
can't wait?

Thanks,
Sean

On Sun, Feb 7, 2016, 8:15 PM DavidBrenner3 <notifications@github.com> wrote:

> Well, I'll do my best to solve it, but you realize I cannot guarantee I
> will.
> As I said, replacing snetcfg is not that easy without its source code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vboxme/Portable-VirtualBox/issues/33#issuecomment-181189414>
> .
>
-- 
-Sean
http://bellriverranch.com

**Comment by DavidBrenner3** [comment]
The official version is here: http://reboot.pro/files/file/339-virtual-machine-usb-boot/
But, like I said, it's not compatible with Portable VBox.

On the next version (1.6) I'm still working  to implement the use of Portable VBox.
I just finished implementing USB and I'm about to start implementing the network services/drivers.
I don't have a github/sourceforge project for it.
But if you guys wanna test it, I can upload it somewhere and give you the link.

**Comment by p060477** [comment]
hi david!
it should be very very gorgeous and beautiful if you will be able to finally let vbox portable completely
workable and compatible with win 10!
as said up to now two main feartures are bugged:
1)no way to use bridge network
2) no bi directional drag n drop

the 1) is very very important..for ex without it there is no way to use emule in vbox with its 2 arrows green..cause there is no way to have the kad not firewalled..
but more other actions are forbidden without network bridged

so we are all only waiting for some good news from you

you really are our new guardian angel!!
having RUNAR shamely disappeared..

cheers!!

**Comment by DavidBrenner3** [comment]
I think I found the problem:
On Windows 10, VirtualBox is using VBoxNetLwf driver/service instead of VBoxNetFlt (see the screenshot).
![virtualbox_windows 10 x64_12_02_2016_08_33_05](https://cloud.githubusercontent.com/assets/9998134/13000580/887df028-d164-11e5-86b1-2350ecbd5388.png)
So, in the AutoIt script, it has to detect Win10 and switch to VBoxNetLwf.

**Comment by p060477** [comment]
hi david!
you really are a Genius!
our angel!
so now how to finally solve this bug and having vbox portable fully compatible with win 10?
i mean the main features as network bridged and bi dir drang n drop
it has been since july 2015 that it really did not work..
pls post here yr solutions!
thxs so much again!!
cheers!
:)

**Comment by runarbu** [comment]
Hi @DavidBrenner3 

This looks like a nice find. I have looed at the headers for both files (https://www.virtualbox.org/svn/vbox/trunk/src/VBox/HostDrivers/VBoxNetFlt/win/drv/VBoxNetLwf.inf and https://www.virtualbox.org/svn/vbox/trunk/src/VBox/HostDrivers/VBoxNetFlt/win/drv/VBoxNetFlt.inf), and both apear to be a "VirtualBox Bridged Networking Driver", but VBoxNetLwf is newer.

I will test this out and see if it fixes the issue.

> We could work together, share resources, exchange ideas and source code and so on - to 
> make both applications better.
>

Sounds great. Is the source code your are working on available somewhere?

Btw, cool to see someone program in Delphi. I used to do so for many years myself, but unfortunately do not get to do it so often this days.

**Comment by DavidBrenner3** [comment]
Source code: https://drive.google.com/open?id=0ByKxAD_t9uvLcU9BM1BiVWFPOWM
Compiled: https://drive.google.com/open?id=0ByKxAD_t9uvLYUNadFFTdWJaeE0
It's a work-in-progress so it may be buggy.
The use of snetcfg and VBoxNeFlt/Lwf aren't implemented, only VBoxNetAdp.

**Comment by DavidBrenner3** [comment]
Command to create VBoxNetLwf service:
sc create VBoxNetLwf binpath= "c:\Windows\System32\drivers\VBoxNetLwf.sys" type= kernel start= auto DisplayName= "VirtualBox NDIS6 Bridged Networking Service"

**Comment by p060477** [comment]
Hi David!
Hi RUNAR!..really glad to see and hear you here again..
pls do a team to solve this so old and great vbox portable bug..here since july 2015
at the start of win 10

@david:
i've launched,with the higher privilegies as administrator, yr:
sc create VBoxNetLwf binpath= "c:\Windows\System32\drivers\VBoxNetLwf.sys" type= kernel start= auto DisplayName= "VirtualBox NDIS6 Bridged Networking Service"

and i got : operations succesfully created!

but if i launch : services.msc i really do not find any vbox portable service at all..
..pls tell me why..
where is my fault..?

**Comment by DavidBrenner3** [comment]
@p060477
 No fault, that's normal.

@runarbu
Even if this problem is solved or not, the AutoIT code of Portable-VirtualBox.exe needs to be changed.
When it cannot load/register/start/copy one or more dlls/drivers/services it should notify the user and let him choose to:
Abort    it will stop loading, then unload what was loaded until the error occurred, then close.
Retry    try again
Ignore   it will ignore the error and continue loading the rest of the dlls/drivers/services.

**Comment by p060477** [comment]
hi david!
first thx so much for yr speed reply!
but if it is normal why i have no vbox service in my services.msc..??
so where is the utility or what is worth to launch in dos yr string:
sc create VBoxNetLwf binpath= "c:\Windows\System32\drivers\VBoxNetLwf.sys" type= kernel start= auto DisplayName= "VirtualBox NDIS6 Bridged Networking Service"

if then there is no trace of that service in services.msc..??

pls apologize my very very poor and few skill..
cheers!!
:)

**Comment by DavidBrenner3** [comment]
Because such services aren't usually visible in services.msc
But you can see/modify them in a cmd console using sc commands:
sc [query/queryex/create/start/stop/delete..] name_of_the_service
That command isn't enough to make the bridge network functional. You need to load the driver and then start the service.
I wrote it for runarbu to help him find the final solution.

**Comment by p060477** [comment]
hi and thxs again!
if i do query i now see it's -stopped-
if i try -start- i get: "impossible..it is not in function.."

..so how to start that VBoxNetLwf  service..?

thxs so much again!!
cheers!!

**Comment by DavidBrenner3** [comment]
Well, sorry but you can't in this moment. Like I said it needs more commands.
runarbu and/or I need to find the right combination of app/ commands to use so it will function properly.
So far we haven't  :(

**Comment by p060477** [comment]
hi and thxs again !
..so we can only anxiously waiting for you to solve this so old and frustrating bug
in order to have finally our vbox portable fully compatible with win 10

thxs again!
pls any step let us know here!!

cheers!!

:)

**Comment by DavidBrenner3** [comment]
"Digging" through Google/VBoxForum/VBoxBugTracker found 2 things:
1. Some time ago the users of the installed VBox had the same problem in Windows 10. At some point the guys from Oracle fixed it.
2. In Windows 10 VBox uses NDIS 6 drivers https://msdn.microsoft.com/en-us/library/windows/hardware/ff556026%28v=vs.85%29.aspx (the current implemented in PVBox are NDIS 5).
For example it uses drivers\netadp6\VBoxNetAdp6 instead of drivers\netadp\VBoxNetAdp.
Most likely snetcfg and devcon aren't fully designed/compatible for/with NDIS 6 drivers...

**Comment by DavidBrenner3** [comment]
@runarbu

I found how VBox setup file is installing/uninstalling its drivers. In the VirtualBox-[version_number]-Win.exe thera are 3 files: VirtualBox-[version_number]-MultiArch_x86.msi, VirtualBox-[version_number]-MultiArch_amd64.msi and common.cab.
Inside each msi installer there are 2 dlls: DIFxApp.dll and DIFxAppA.dll. They can be extracted using Orca or the msi TC plugin. Not all msi unpackers see them, because they are in the Binary section not the Files section.

![clipboard01](https://cloud.githubusercontent.com/assets/9998134/13105362/7be7c7c0-d56b-11e5-86c3-956497529a0d.png)

According to the msi script, DIFxApp.dll is used to "ProcessDriverPackages" and "CleanupOnSuccess". DIFxAppA.dll is used for "InstallDriverPackages", "UninstallDriverPackages" and "RollbackInstall".

![clipboard02](https://cloud.githubusercontent.com/assets/9998134/13105379/915f6eaa-d56b-11e5-9b38-7cae406a62fb.png)


So, one way to solve this problem is to figure out how to extract them from the setup exe file and how to use them to install/uninstall drivers.

Another way:

I found most part of the snetcfg code in another github project.
Unfortunately is in C++ and my knowledge in C++ is not that great.
I was able to port the C++ functions for installing and uninstalling drivers from devcon into Delphi code in a few days but, comparing with the work required to fix snetcfg, it was a "walk in the park".
SnetCfg is using the INetCfg interface to install/uninstall network drivers. The problem is there is no "translation" of this interface into Delphi/Pascal language (says Google). That's making it more difficult to understand and use.

Third way:

You can follow the instructions from this link: https://www.virtualbox.org/wiki/Windows%20build%20instructions
It says to use Loadall.cmd to register the drivers. Loadall.cmd starts an sh script; the script uses NetLwfInstall.exe/NetAdp6Install.exe/NetFltInstall.exe/NetAdpInstall.exe to install/uninstall the drivers.
These files are available only after the compilation.
You can use them to install/uninstall network drivers in the portable version.

Fourth way:

You can trace the code from those exe files, found how they use INetCfg interface and make+compile your own utilities. Unfortunately the code is not so easy to "trace".



The problem with each solution is that requires some work to be done...
But if you decide to try you can count on my help.

https://drive.google.com/file/d/0ByKxAD_t9uvLZExwbnpRSGtnelE/view?usp=sharing

**Comment by p060477** [comment]
hi david!
first so much thxs again for yr kind interest and helping!
i don't know if it could help but ptoblems with network bridged started with win 8 and 8.1
at that moment it started the frusstrating pop up error about snetcfg..
at that moment i solved by put in the task scheduler the vbox process..so starting the pc
vbox started and i bypassed probably that wins control...
obviously i already tried the same with win 10 but with no results at all..

another idea: with win 10 lots of frewalls and anti viruses fails due to the fact that win 10 has its own..
and win 10 has also its own virtualization..so may be -that's the question-...

hoping to finally be able to use -completely- vbox portable with win 10 also in its
network brudged and bi diretional drag and drop i only can wait for yr useful trying and ideas!!

**Comment by likvidera** [comment]
@DavidBrenner3 @runarbu I am also in the process of fixing the portability.

As for the [DIFx tools](https://msdn.microsoft.com/en-us/library/windows/hardware/ff553644(v=vs.85).aspx) You can get the DPinst.exe from the WDK. I am uncertain if the API goes further than what the compiled binary does. 

The binary tool doesn't seem to want to install the network drivers though or I'm missing something, like the need for .inf entries.

However, on Windows 10 with the latest version of VirtualBox(5.0.14) i can successfully install the network drivers using:

`c:\\tools\\devcon_x64.exe install c:\\VirtualBox\\drivers\\network\\netadp6\\VBoxNetAdp6.inf sun_VBoxNetAdp`
From the .inf directory
`c:\\tools\\snetcfg_x64.exe -v -l VBoxNetLwf.inf -m VBoxNetLwf.inf -c s -i oracle_VBoxNetLwf`

The tools are from the latest portable-vbox. This at least, adds the VirtualBox adapter with the filter in my network devices and I can use the bridge option in VirtualBox.

As for portability as a whole, for the teardown I am currently failing to correctly remove the VBoxUSB and VBoxUSBMon, trying to stop the latter puts it in a infinite pending state. It's the only missing piece for me.

**Comment by DavidBrenner3** [comment]
Thank you for the info.

I tried this too some time ago and it didn't work (the console window froze).
I tried again today and it works. Weird...
Looks like W10 still fails on stability.

Btw, forgot to mention: the latest VBox versions are using NDIS 6 drivers in Vista/7/8/8.1 too.
I tested in 8.1 and indeed works.
So now Portable VBox can be set too to use the NDIS 6 drivers by default.
If it founds XP, it will switch to NDIS 5.

Ok, so now we'll wait until runarbu modifies the script, recompiles, adds the digital signature and uploads it to website.


As for your problem with the VBoxUSBMon service: I don't have this problem, so the cause may be on your computer. Could be a USB device/driver which the service fails to recognize. Try to remove all USB devices and unnecessary drivers and see if it still does the same.
If it doesn't, add the USB devices one at a time and detect which one(s) trigger the problem. And notify Oracle using the bugtracker.
If it does, try with the latest installable VBox version. If it still does, notify Oracle. If it doesn't, uninstall it and use the latest version in the portable version. If it still does the problem then come back here and open an issue.

**Comment by likvidera** [comment]
@DavidBrenner3 I realised my mistake yesterday, at least in later versions of VirtualBox or in Windows 10 the VBoxUSB is not installed only the VBoxUSBMon. When leaving out VBoxUSB from my install script it seems to works just fine now.

**Comment by DavidBrenner3** [comment]
No problem, glad that the problem is solved :)

**Comment by p060477** [comment]
hi 
but now is there a way to have portable vbox fully compatible with win 10..??
i mean the network bridge and the bi directional drag and drop..for istance..

**Comment by DavidBrenner3** [comment]
Yes, thanks to likvidera:

![windows 10 x64_24_02_2016_12_29_59](https://cloud.githubusercontent.com/assets/9998134/13282739/19215678-daf3-11e5-9425-9a6a4fc30b9b.png)

The only problem is, the first time you try to install VBoxNetLwf in W10, snetcfg freezes. You have to reboot but after that it works.

**Comment by p060477** [comment]
so which are the exact steps to do..??..
could you pls give us a small simple detailed guide..?
works also with new 5.0.15 or latest stable 5.0.14..?
cheers!!

**Comment by p060477** [comment]
"Ok, so now we'll wait until runarbu modifies the script, recompiles, adds the digital signature and uploads it to website."..:
on the vbox.me site is only there the very old 5.08...
and runar semms as the canterville ghost...
or hudini...

**Comment by DavidBrenner3** [comment]
I'm not sure if an automated solution to install/uninstall only Net drivers can be found, especially because VBox needs to be closed during this. But, if VBox is closed, Portable-VirtualBox.exe is closing too. And, when it's closing, it removes the path to Portable VBox files from Windows environment.
Options:
1. Wait until runarbu modifies the script.
2.  Deactivate the load of network drivers in Portable VBox and load/unload the drivers manually each time, hoping it will work with VBox window open.
3. Use my app, it's tested with 5.0.14 on my computer. But, since it's still in developement stage, I cannot guarantee it will work on any computer...
BTW, do not use my app and Portable-VirtualBox.exe in the same time.

https://drive.google.com/open?id=0ByKxAD_t9uvLYUNadFFTdWJaeE0

**Comment by p060477** [comment]
hi david!
thx again!

1)..runar as incredibly disappeared..are you able to do it..??..
2) how to do it..??..pls tell us the each steps..we are not so skilled..!!
3) is it portable..?..is there a detailed guide for no skilled as us..??

cheers!!

**Comment by p060477** [comment]
for likvidera:
"However, on Windows 10 with the latest version of VirtualBox(5.0.14) i can successfully install the network drivers using:

 c:\\tools\\devcon_x64.exe install c:\\VirtualBox\\drivers\\network\\netadp6\\VBoxNetAdp6.inf sun_VBoxNetAdp 
 From the .inf directory
 c:\\tools\\snetcfg_x64.exe -v -l VBoxNetLwf.inf -m VBoxNetLwf.inf -c s -i oracle_VBoxNetLwf 

The tools are from the latest portable-vbox. This at least, adds the VirtualBox adapter with the filter in my network devices and I can use the bridge option in VirtualBox"

could you please give us a detailed step by step guide..??
consider we are not so skilled...
thxs in adv!

cheers!!

**Comment by DavidBrenner3** [comment]
1. Not 100%. I'm not familiar with AutoIT script language so it will take some time to modify the script. Plus I don't have access to the USB device for adding the digital signature or the site files.
2. You can use this scripts:

[register_network.zip](https://github.com/vboxme/Portable-VirtualBox/files/144556/register_network.zip)
[unregister_network.zip](https://github.com/vboxme/Portable-VirtualBox/files/144555/unregister_network.zip)

Open them in Notepad/Wordpad and modify the first line by replacing the path after '=' with the path to your Portable VBox files (where app32/app64 folders are). Be sure that it will not end with '\'.
Start Portable VBox with no network and start register_network.cmd as administrator.
Before closing Portable VBox, start unregister_network as administrator.
3. If you would of opened the zip file from the link, you would of noticed that it has both the installed and the portable version. Plus, it has the 32 bit and the 64 bit.
Start the exe, go to options, set the path to VirtualBox.exe and to load the network too. Click on ok and wait till the arrow from the up right corner becomes green again (from red). It will take a few sec, especially if it is the first time.
If all is ok, no message window will appear.
To start the VB manager, click on the Manager button from the right  and then on the VB Manager in the popup menu.
To start the VB Manager directly with the button, you can create a dummy VB entry in the application and make sure is always selected. This way the VB Manager icon will be displayed in the button and it will open it directly.

Good luck.

**Comment by p060477** [comment]
hi david and so many thxs again!
the path is:
G:\VIRTUALBOX-TESTS\Portable-VirtualBox 5.0.15\app64
so i place that in first line..but..when i launch it with admin right,
i've win 10 home 64 bit..,i got impossible to find the specified path..why..??
Impossibile trovare il percorso specificato.
Impossibile trovare il percorso specificato.

G:\VIRTUALBOX-TESTS\Portable-VirtualBox 5.0.15\app64>"G:\VIRTUALBOX-TESTS\Portable-VirtualBox 5.0.15\app64\data\tools\devcon_x64.exe" install "G:\VIRTUALBOX-TESTS\Portable-VirtualBox 5.0.15\app64\app64\drivers\network\netadp6\VBoxNetAdp6.inf" "sun_VBoxNetAdp"
Impossibile trovare il percorso specificato.
Impossibile trovare il percorso specificato.

G:\VIRTUALBOX-TESTS\Portable-VirtualBox 5.0.15\app64>"G:\VIRTUALBOX-TESTS\Portable-VirtualBox 5.0.15\app64\data\tools\snetcfg_x64.exe" -v -l "app64\drivers\network\netlwf\VBoxNetlwf.inf" -m "app64\drivers\network\netlwf\VBoxNetlwf.inf" -c s -i oracle_VBoxNetLwf
Impossibile trovare il percorso specificato.
Finished
Premere un tasto per continuare . . .

**Comment by p060477** [comment]
and using yr tool this is what i get..i attached a screen shoot..not able to see and so to push the -ok- button..why..??
![david tool](https://cloud.githubusercontent.com/assets/12773559/13295072/5d5183c0-db27-11e5-86df-cad787ab0703.jpg)

**Comment by p060477** [comment]
david..as you can see here there are only some certain things..:
1) runar has astonishingly and incredibly disappeared..so you are our only guardian angel..
2) we really are not skilled at all..so you if are so kind you have to make a tutorial -step by step- with all of fully details to do..as you were talking with a new born child..

we really hope you will have the patience to help us to solve this matter that is here since the very late july 2015...

so many thxs indeed in adv..

cheers!

**Comment by DavidBrenner3** [comment]
Your path is G:\VIRTUALBOX-TESTS\Portable-VirtualBox 5.0.15 not G:\VIRTUALBOX-TESTS\Portable-VirtualBox 5.0.15\app64

Your computer has the Screen height too small and the window is bigger, the OK button is below the taskbar. Try to click in an edit box (for example where the path to VBox is set) and press Return.

**Comment by p060477** [comment]
"Try to click in an edit box (for example where the path to VBox is set) and press Return."..:

..i just set the path as you can see in my photo..but...the ok button did not appear at all..
..and where is -retur- to press..??
pls have the patience to help me..apologize my few skills..
cheers!!

**Comment by DavidBrenner3** [comment]
"Return" key on your keyboard. Try to find the italian translation...

**Comment by p060477** [comment]
i got this now..
![error](https://cloud.githubusercontent.com/assets/12773559/13296515/3247b832-db2e-11e5-8cfc-3820b38dcc60.jpg)

**Comment by DavidBrenner3** [comment]
Close the program, restart your computer and try agan.
If it still doesn't work try with the scripts.

**Comment by p060477** [comment]
hi!
now it works..in this way:
when i start vbox my vm machine is not accessible..so i have to delete it and to re-attach it again..
so the vm starts and, is a win xp pro, i got this pop up that attaches..and i'm not able to navigate..i mean that internet did not function..
if i try nat insted i navigate..so now i'm able to run the vm with network bridge..but i'm not able to navigate..why..??
![error2](https://cloud.githubusercontent.com/assets/12773559/13296946/3a596f00-db30-11e5-9cf2-cac4a1108a44.jpg)

**Comment by DavidBrenner3** [comment]
That popup means you have to copy that file in that location.
That's common knowledge..

And regarding the internet problem: you have to give me more informations, not just "is not working" so I will be able to help you.

**Comment by p060477** [comment]
hi david!
first thxs so much again indeed for all yr precious time and patience you are gifting to me!
i told you i was really not skilled at all..but..with yr precious helping,you really are my guardian angel!,:
1) now i'm able to navigate with network bridge after 7 months,from win 10 july 2015 starts, of
deep nightmare!
is really all due to your KIND AND PRECIOUS helping and aging! so many thxs again!
2) remains still the drag and drop issue..:
i'm able to drag and drop ONLY from VM ,win xp pro, to my real machine win 10 home 64
but NOT from my real machine to my virtual one..have you any idea about this..?
when i've my old win xp as real machine, up to the latest win 8.1, i was able to have bi-directional drag and drop..so is a matter of win 10 i suppose..what you think..?

3) about yr very wonderfull and precious tool i'd like also to use other of its possibilities..have you a simple guide about it..??..for example if i try to use the -manager- button i get this error:
![manager](https://cloud.githubusercontent.com/assets/12773559/13310927/9116d7a6-db8a-11e5-8552-5c6e99d2f955.jpg)...why..??
have you still a little space of patience and time to gift to me..consider that you have not to forget that you are speaking to a non skilled guy..so you have to consider me as a little new born child...

many many THANKS again indeed and FOREVER

cheers!!

Giusy

**Comment by Forgen** [comment]
Brilliant work David.  Thank you

On Wed, Feb 24, 2016, 9:42 PM p060477 <notifications@github.com> wrote:

> hi david!
> first thxs so much again indeed for all yr precious time and patience you
> are gifting to me!
> i told you i was really not skilled at all..but..with yr precious
> helping,you really are my guardian angel!,:
> 1) now i'm able to navigate with network bridge after 7 months,from win 10
> july 2015 starts, of
> deep nightmare!
> is really all due to your KIND AND PRECIOUS helping and aging! so many
> thxs again!
> 2) remains still the drag and drop issue..:
> i'm able to drag and drop ONLY from VM ,win xp pro, to my real machine win
> 10 home 64
> but NOT from my real machine to my virtual one..have you any idea about
> this..?
> when i've my old win xp as real machine, up to the latest win 8.1, i was
> able to have bi-directional drag and drop..so is a matter of win 10 i
> suppose..what you think..?
>
> 3) about yr very wonderfull and precious tool i'd like also to use other
> of its possibilities..have you a simple guide about it..??..for example if
> i try to use the -manager- button i get this error:
> [image: manager]
> <https://cloud.githubusercontent.com/assets/12773559/13310927/9116d7a6-db8a-11e5-8552-5c6e99d2f955.jpg>
> ...why..??
> have you still a little space of patience and time to gift to me..consider
> that you have not to forget that you are speaking to a non skilled guy..so
> you have to consider me as a little new born child...
>
> many many THANKS again indeed and FOREVER
>
> cheers!!
>
> Giusy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vboxme/Portable-VirtualBox/issues/33#issuecomment-188623289>
> .
>
-- 
-Sean
http://bellriverranch.com

**Comment by DavidBrenner3** [comment]
@p060477
My application and Portable-VirtualBox.exe should not be used in the same time.
Most probably you started my application and then you closed Portable-VirtualBox.exe.
Portable-VirtualBox.exe unregistered the VBox dlls/infs/drivers and when my app tried to start the VBox Manager it's obvious why it couldn't.

Regarding the drag'n'drop problem, i'll try to find a solution.

@Forgen 
You're welcome.
But likvidera deserves thanks too https://github.com/vboxme/Portable-VirtualBox/issues/33#issuecomment-186471051

**Comment by p060477** [comment]
hi david!
yes likvidera has given usefull info but only for skilled people as you
instead YOU have given useful info and a brilliant tool too for not skilled at all people as us!!

you say:
"My application and Portable-VirtualBox.exe should not be used in the same time.
 Most probably you started my application and then you closed Portable-VirtualBox.exe."

so which is the right sequence..?..
if i start yr tool and ,not having already start vbox portable, i push yr -manager- button is ok..?

and about this:
"To start the VB Manager directly with the button, you can create a dummy VB entry in the application and make sure is always selected. This way the VB Manager icon will be displayed in the button and it will open it directly."..:

could you pls give a step by step guide to do so..?..considering my very poor knowledge and skills..

thxs so much again and forever!

cheers!!

giusy

**Comment by DavidBrenner3** [comment]
Right sequence:
To use Virtual Machine USB Boot: close Portable-VirtualBox.exe (if it's opened), wait till is closed, start Virtual Machine USB Boot, wait till the arrow is green and use it. Don't start Portable-VirtualBox.exe.
To use Portable-VirtualBox.exe: close Virtual Machine USB Boot (if it's opened), wait 5..15 sec, start Portable-VirtualBox.exe, wait till is fully started and use it. Don't start Virtual Machine USB Boot.

To add an entry to the Virtual Machine USB Boot and select it, start Virtual Machine USB Boot, wait till the arrow is green, click on Add button (blue cross),
In "VM name" dropbox, select one of the Virtual Machines from VBox. In "Drive to add and boot" select one of the drives from your computer (if there isn't one displayed insert a USB stick/flash and restart the window).
Click on OK, the Add window will close.
You'll notice now the new added entry is selected and the icon from the Manager button is changed to VBox icon.
Now if you click on button it will start VBoxManager directly.

**Comment by p060477** [comment]
hi david and txs again!
yr guide is very detailed!
but if i exit first yr tool and then start portable vbox there is the problem with the drivers so network bridge won't works..
am i wrong..?

**Comment by DavidBrenner3** [comment]
If you want to use the portable VBox without using my app you should use the scripts to load/unload network drivers.

Selct any drive you want, it doesn't matter.

**Comment by p060477** [comment]
hi and thxs!
apologize my skills..may be i've misunderstood or not explain me well..apologize...
i re try..:

i start yr tool and the red cross became green..but then how to use my portable vbox..?
i have to start it to use it and i want to use it with network bridge...so if i close first yr tool 
how to use it with network bridge..?

**Comment by DavidBrenner3** [comment]
Start my tool, be sure the network is checked in options, start VBox Manager with the button and from there start any VM you want.

**Comment by p060477** [comment]
hi and thxs !
first i've to add the vm in yr tool with yr blu cross?
anyway i've tried to start first yr tool and then with it opened i started portablevbox 
and it works fine with bridge network
the only thing that was not able to do was to use yr tool's manager button to do what
i've said before ...
cheers!
giusy

**Comment by p060477** [comment]
hi david!
yr fantastic tool really intrigue and pleased me!
1) when i choose the drive it shows me only 2 HDD of mine but i've 3 ones:
    200gb maxtor, 500gb maxtor, and 1000gb toshiba...but yr tool recognized only the first 2
    not the 1000gb toshiba one..is there any reason?
2)what about the tab:"enable vt-x/amd-V..?..whta is its meaning?

3) at the end i got the picture attached..you say that:
    "Now if you click on button it will start VBoxManager directly.
You only need to do this once, next time you start Virtual Machine USB Boot it will load the entry and it will select it. (if it was selected at the moment it was previously closed)."..:
but i've -always- to click the -manager- button on the right..otherwise i got the picture i attached but the vbox manager do not start at all..where is my fault..??:
![david s tool](https://cloud.githubusercontent.com/assets/12773559/13326745/6d015d5c-dbe7-11e5-9142-fe7e5eb71da0.jpg)


thxs so much again..also for yr kind patience!!

cheers!!

giusy

**Comment by p060477** [comment]
Hi David!

now i'm able to use fully yr tool!
is very very FANTASTIC!
it has resolved the network bridge bug that was there since july 2015!

..now it remains only the drag and drop issue,
from host win 10 to guest win xp..

have you ahy ideas why the drag and drop works only from guest xp to host win 10..?

thxs so much again indeed for the great gift you done to us!!

cheers!!

**Comment by p060477** [comment]
Hi David!

now i'm able to use fully yr tool!
is very very FANTASTIC!
it has resolved the network bridge bug that was there since july 2015!

..now it remains only the drag and drop issue,
from host win 10 to guest win xp..

have you ahy ideas why the drag and drop works only from guest xp to host win 10..?

thxs so much again indeed for the great gift you done to us!!

cheers!!

**Comment by p060477** [comment]
Hi David!

now i'm able to use fully yr tool!
is very very FANTASTIC!
it has resolved the network bridge bug that was there since july 2015!

..now it remains only the drag and drop issue,
from host win 10 to guest win xp..

have you ahy ideas why the drag and drop works only from guest xp to host win 10..?

thxs so much again indeed for the great gift you done to us!!

cheers!!

**Comment by p060477** [comment]
Hi David!

now i'm able to use fully yr tool!
is very very FANTASTIC!
it has resolved the network bridge bug that was there since july 2015!

..now it remains only the drag and drop issue,
from host win 10 to guest win xp..

have you ahy ideas why the drag and drop works only from guest xp to host win 10..?

thxs so much again indeed for the great gift you done to us!!

cheers!!

**Comment by p060477** [comment]
Hi David!

now i'm able to use fully yr tool!
is very very FANTASTIC!
it has resolved the network bridge bug that was there since july 2015!

..now it remains only the drag and drop issue,
from host win 10 to guest win xp..

have you ahy ideas why the drag and drop works only from guest xp to host win 10..?

thxs so much again indeed for the great gift you done to us!!

cheers!!

**Comment by DavidBrenner3** [comment]
Sorry for not answering sooner but I am extremely busy lately (family problems and other).
I barely had time to make an account on github for my tool and to solve some bugs.
https://github.com/DavidBrenner3/VMUB
You should download the new version, it's a little more stabler.

To have a chance to solve the problem with drag'n'drop I have to use all my resources for it, but, like I said, have to solve other problems first.
So I can't say when it will be solved. Just that I will try as soon as possible.

**Comment by p060477** [comment]
HI DAVID!
you really do not have any meaning to apologize or to say sorry!
we are really in credit with you and all yr precious work and time you gifted to us!
we never should be able to thank you enough!

i go here.
https://github.com/DavidBrenner3/VMUB

..but which is the exact object or link to download..?..
as you know i'm really not an expert at all..sorry...:(

i really wish you all the best!
..expecially for yr familiar problems...
i really hope you will be able to get rid of them

good luck!

and so many thanks again and FOREVER!!

cheers!!
giusy

**Comment by p060477** [comment]
hi david!
i dl yr new vers of yr tool..but now..i always get this frustrating error..:
![error](https://cloud.githubusercontent.com/assets/12773559/13374628/b94ab196-dd8a-11e5-96f9-6418e2a6929b.jpg)

and i'm not able to solve..
where is my fault..??
i've rebooted so many times invain..
pls help!!
cheers!!

**Comment by DavidBrenner3** [comment]
Happens to me too from time to time, no matter if I try with my tool, the scripts or even with the installed version.
It usually happens when you try to register VBoxNetLwf again without unregistering it first.
You already tried rebooting.
Ok, try the unregister script a few times and then try the register script.. In a cmd console try this command:
sc queryex vboxnetlwf
And copy here the result.

**Comment by DavidBrenner3** [comment]
I also uploaded a new version of my tool.
Now it works in "paranoid" mode: before installing VboxNetLwf, it "cleans" any trace of previous installs, no matter if Windows reports that is clean.

**Comment by DavidBrenner3** [comment]
Updated the scripts to work in the same way:

[register_network.zip](https://github.com/vboxme/Portable-VirtualBox/files/149743/register_network.zip)
[unregister_network.zip](https://github.com/vboxme/Portable-VirtualBox/files/149744/unregister_network.zip)

Good luck.

**Comment by p060477** [comment]
oh magnificent and gorgeous David!
you really are my guardian ANGEL!
i've dl yr precious tool from here:
https://drive.google.com/file/d/0ByKxAD_t9uvLYUNadFFTdWJaeE0/view?pref=2&pli=1

and now everything return FINE!!
and i've not to reboot indeed!!
all now seems to work fine and well!!

1)apologize my very few knowledge and skill..but..
   here: https://github.com/DavidBrenner3/VMUB
   is there any other tool of yours to be downloaded..?
2) so now with yr updated tool there will be no surpirse in future to see again
    that very frustrating pop up error window i've attached and that make me have the fear
    to live again the nightmare lived in this 7 months since july 2015?

3) here it is yr command line first launched without having started yr precious tool
    and it returns no service, then having started yr tool, and it shows the service running!:
    Microsoft Windows [Versione 10.0.10586]
(c) 2015 Microsoft Corporation. Tutti i diritti sono riservati.

C:\WINDOWS\system32>sc queryex vboxnetlwf
[SC] EnumQueryServicesStatus:OpenService OPERAZIONI NON RIUSCITE 1060:

Il servizio specificato non esiste come servizio installato.


C:\WINDOWS\system32>sc queryex vboxnetlwf

NOME_SERVIZIO: vboxnetlwf
        TIPO                   : 1  KERNEL_DRIVER
        STATO                  : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        CODICE_USCITA_WIN32    : 0  (0x0)
        CODICE_USCITA_SERVIZIO : 0  (0x0)
        PUNTO_CONTROLLO          : 0x0
        INDICAZIONE_ATTESA     : 0x0
        PID                    : 0
        FLAG                   :

C:\WINDOWS\system32>

4)you really are a GENIOUS!!

5) good luck to you too!!..expecially for yr problems in yr family

i wish to you all the best from the very deep of my heart!!

cheers!!

giusy

**Comment by DavidBrenner3** [comment]
Just this tool.

Well, nobody can be 100% sure that it will never popup again but I can say the chances to appear again are low.

**Comment by p060477** [comment]
hi David!
thxs again!

a curiosity:
why the -manager- of yr tool see only 2 hdd of my 3 ?..it sees only the 2 maxtor but not the 1000gb toshiba one..?

and more importat thing you say:
"Btw, these dlls/drivers/services aren't designed to be loaded/unloaded every time you open/close VirtualBox. Also, the service/drivers management from Windows is also not designed for this.
For example, my W8.1 OS, after so many tests with the scripts and my tool, it's barely "alive". I have to use the backup soon. "..:

what does it really means..??
could you pls explain in a more simple way as you were talkin with a new born child..?
i do not understand how that could be interfere with the wealth of the o.s....
up to win 8.1 with my portable vbox every time , using the network bridge, i see the vbox drivers
loaded at the start and unloaded at the end..and i really do not have any problem with my o.s....
every vbox portable did that in the past...i used it since my first win xp up to win 7 and 8 and 8.1
with no issues with my o.s...
now yr words really worried me a bit..

thxs so much!!
cheers!

giusy

**Comment by DavidBrenner3** [comment]
It sees only 2 out of 3 because it was designed to not show the HDD where the OS is installed (Windows).
My tool boots real HDDs/sticks/flash drives into a QEMU/VBox VM by partially disconnecting them from the Windows OS (from the host computer).
But you cannot disconnect the HDD with the OS files. And, even if you would find a way, it's a bad idea anyway, because normal Windows OSs can't be separated from their installed files.
So my tool sees that HDD but it doesn't display it in the list.


Every time you use an OS and every time you start/use/close an application you "shorten" their "lifespan" a bit. That's why they need to be reinstalled periodically.
Usually a portable application is more robust and "damages" the OS less, but with one condition: to be designed to be portable from the start. VBox is not.
Installing/uninstalling drivers and services every time you start/close VBox "damages" the OS a little more than starting a normal app.
People use portable apps for 2 reasons:
1. to be able to use their favorite apps on any computer without installing/setting and so on;
2. to keep the OS "fresh" and fast.
For the first, especially because it's done rarely and on many computers, there are no problems.
For the second, there could be, especially when you start and close Portable VBox a lot.
An analogy: you buy a car to avoid walking long distances, you use it often, but you park it several miles/km away to keep the usual place free for something else. But you end up walking a lot to the place where you park it.
But you don't have to worry that much, just a bit. In the past few weeks, I started/closed Portable VBox more than a 1000 times, probably a lot more than you do in the same amount of time.

**Comment by p060477** [comment]
hi David!

thxs so much indeed for yr very clear reply!!
also a very little skilled at this problems as me have understood!

a curiosity: is there a way,apart obviously to use less yr tool and load unload drivers,
to compensate this stress to my os..?
i mean have i to run some tools to clean it or its registry?
if yes which..?

cheers!!

giusy

**Comment by p060477** [comment]
hi David!
thinking again at yr so clear and detailed above explain about the injuries to the os
i understand that those are NOT only if we use yr precious tool..
cause also in the past before the july 2015 so before win 10
when vbox portable worked well in bridge network every time there was a creation of virtual drivers
so the loand and unload of dlls and so on..
am i wrong..??

cheers!!

giusy

**Comment by DavidBrenner3** [comment]
It doesn't matter if you use my tool, the exe from Portable VBox or a script. The effect is the same.

Couldn't find any good tool to fix the OS. The only good solution is to make a backup after you installed it and set it just the way you like, and then revert/recover from backup from time to time.

**Comment by p060477** [comment]
hi david!
first how are you and how are going yr personal problems?
i hope fine...
i see that on vbox.me there is  now and upgraded portablevbox vers 5.016..but is it now compatible also in network bridge or has it the same old issues?
i mean that if the new vers has now the tricks you suggested to the runar's buvik  ghost to make it's creature finally compatible with win 10..

and the bi directional drag and drop issue..??..
have you found a trick also for that old issue/bug..??

thxs so much in adv!!
cheers!!

**Comment by p060477** [comment]
..maybe also David has gone..with runar buvik..
..what a pity...
:(

**Comment by slrslr** [comment]
@vp060477 some of your comments are very inpolite. You were aready explained why issue is not yet fixed, yet you continue bothering. Example [this post of yours](https://github.com/vboxme/Portable-VirtualBox/issues/33#issuecomment-164662429) is 2 posts above it explained and yet, you decided to whine.

**Comment by p060477** [comment]
oh..!..we've discovered runar's guardian angel !!
pls tell us where is runar..maybe in his canterville's home..
what a pity..what a real shame..
:(
thumb upsidedown..

**Comment by audinue** [comment]
This thread is funny as hell :smile:

**Comment by p060477** [comment]
..if you consider -funny- the runar's and now david brennen's disappearing like houdinies..

**Comment by ReinRalle** [comment]
Hi,

what works for me is to make a launcher for this ("Lauch Portable-VirtualBox.exe") with the following bat file ("Lauch Portable-VirtualBox.bat")

`
@echo off

sc stop vboxnetlwf
sc start vboxnetlwf

Portable-VirtualBox.exe

sc stop vboxnetlwf
`
then i make an exe from this batch with [Bat to Exe](http://www.f2ko.de/en/b2e.php) (add admin manifest).

not perfect but quick and dirty ;-)

Ralf

**Comment by ReinRalle** [comment]
Hi,

here is my last work on this Issue (for discussion)

Please have mercy - this is my first AutoIt Prj

need: [mindinst.exe](http://it.bmc.uu.se/andlov/win32/proj/mindinst/)
need: pnputil.exe, sc.exe, net.exe (Win10)

It works 4me under: 3.3.14.2/X64, AdminMode, OS: WIN_10/X64, OSLang: 0407

for suggestions I am grateful

Ralf R. (ReinRalle/Germany) 25.07.16 - 13:58 h
 
[Au3 Code](http://pastebin.com/cCMDhmB9)

**Comment by 1988fido** [comment]
any update guys? :D did you manage to make a tool that works on windows 10 to run virtual portable stuff ?

i am really interested and actually need it :/ tried LiLi and virtualbox portable no luck , with some tinkering here and there but couldn't get anything to work on win10

**Comment by p060477** [comment]
thxs 1988fido...maybe Runar is still not interested in to make finally truly workable vbox portable with win 10..may be is just waitin for the new wins operative system..??..
:(
